<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Create resident reports.
     */
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            $table->id();

            // Resident who submitted the report
            $table->foreignId('user_id')
                ->constrained()
                ->cascadeOnDelete();

            // Generated by Laravel after the report is created.
            // Example: EM-000001 or NE-000002
            $table->string('report_code', 30)
                ->nullable()
                ->unique();

            // Emergency or Non-Emergency
            $table->string('report_type', 30)
                ->index();

            // Internal concern identifier from the frontend.
            // Example: flood, medical, road-obstruction
            $table->string('concern_code', 80);

            // Human-readable concern.
            // Example: Flood Rescue Needed
            $table->string('concern_type', 150);

            // Optional non-emergency subcategory
            $table->string('subcategory', 150)
                ->nullable();

            // Current workflow state
            $table->string('status', 80)
                ->index();

            // Assigned by backend/business rules
            $table->string('priority', 30)
                ->index();

            // Myself or Another Person
            $table->string('reporting_for', 30)
                ->default('Myself');

            // Person affected by the report, when applicable
            $table->string('subject_name', 150)
                ->nullable();

            $table->string('subject_contact', 30)
                ->nullable();

            $table->string('relationship_note', 150)
                ->nullable();

            // Incident location
            $table->string('purok', 100)
                ->nullable();

            $table->text('location');

            $table->string('landmark', 255)
                ->nullable();

            // Ready for future map/geolocation integration
            $table->decimal('latitude', 10, 7)
                ->nullable();

            $table->decimal('longitude', 10, 7)
                ->nullable();

            // Main resident-provided information
            $table->text('description')
                ->nullable();

            $table->text('required_assistance')
                ->nullable();

            // Example:
            // ["Child", "Senior Citizen", "PWD"]
            $table->json('affected_individuals')
                ->nullable();

            // Relative Laravel storage path
            $table->string('photo_path')
                ->nullable();

            // Barangay-side information
            $table->text('barangay_remarks')
                ->nullable();

            $table->text('invalid_reason')
                ->nullable();

            $table->text('resolved_remarks')
                ->nullable();

            $table->timestamps();

            // Useful for resident report queries
            $table->index([
                'user_id',
                'status',
            ]);

            $table->index([
                'user_id',
                'created_at',
            ]);
        });
    }

    /**
     * Remove resident reports.
     */
    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
